X, T = np.meshgrid("%d", t)
    fig = plt.figure()
    ax = fig.add_subplot(111, projection='3d')
    ax.plot_surface(X, T, u.T, cmap='viridis')
    ax.set_label('x')
    ax.set_ylabel('t')
    ax.set_label('U(x, t)')
    plt.show()